theme="tokyonight"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
color-modes = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "â†—ï¸"
mode.insert = "âœï¸"
mode.select = "ğŸ‘‰"
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "i"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.lsp]
display-messages = true
